### ISSUE TITLE
Not a valid response from HTTP 

### ISSUE THREAD

**Issue by shahidzebpay** [TronWatch/tron-http-server#2]
It gives response like this

EqsBCmYIsPqiosYsEiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABogAAAAAAAEEHkdBMwzdl/UuNYNO+xJvegDkyLkg3UusRU4+qAQShVBHXq6E+oZmmPRZH5Y45wWqbudpokSQfxnfECjXLYITRq7clJl154IEnS1fu04MNLFmzajzUblSuKSkg11Xd14B7cnZEqYuMPGuKG2iob/RadczYLPy4MA

I have used the latest block http api

**Comment by metjm** [comment]
thats a base64 encoded grpc response. You can find examples how to decode them here https://github.com/TronWatch/tron-http-client/blob/master/index.js

**Comment by shahidzebpay** [comment]
Any thoughts on getTransactionById function? I am doing this like this:

    const data = await tronNode.getTransactionById(tx)    
    return data.toObject()

it crashes. Any help would be appreciated.

**Comment by metjm** [comment]
whats the tronNode object? what are you using to communicate with the node?

**Comment by metjm** [comment]
also, whats the error that is being thrown?

**Comment by shahidzebpay** [comment]
const tronNode = caller("ec2-18-185-51-137.eu-central-1.compute.amazonaws.com:50051", WalletClient)

error is

Error: Expected argument of type protocol.BytesMessage
    at serialize_protocol_BytesMessage (/home/shahid.shaikh/proje
cts/eos-proxy/node_modules/tron-http-tools/protocol/api/api_grpc_
pb.js:122:11)
    at Object.final_requester.sendMessage (/home/shahid.shaikh/pr
ojects/eos-proxy/node_modules/grpc/src/client_interceptors.js:802
:37)
    at InterceptingCall._callNext (/home/shahid.shaikh/projects/e
os-proxy/node_modules/grpc/src/client_interceptors.js:418:43)
    at InterceptingCall.sendMessage (/home/shahid.shaikh/projects
/eos-proxy/node_modules/grpc/src/client_interceptors.js:460:8)
    at InterceptingCall._callNext (/home/shahid.shaikh/projects/e
os-proxy/node_modules/grpc/src/client_interceptors.js:424:12)
    at InterceptingCall.sendMessage (/home/shahid.shaikh/projects
/eos-proxy/node_modules/grpc/src/client_interceptors.js:460:8)
    at ServiceClient.Client.makeUnaryRequest (/home/shahid.shaikh/projects/eos-proxy/node_modules/grpc/src/client.js:496:21)    at apply (/home/shahid.shaikh/projects/eos-proxy/node_modules
/lodash/lodash.js:478:17)    at ServiceClient.wrapper [as getTransactionById] (/home/shahid.shaikh/projects/eos-proxy/node_modules/lodash/lodash.js:5337:16
)    at callback (/home/shahid.shaikh/projects/eos-proxy/node_modu
les/promisify-call/index.js:32:8)

**Comment by metjm** [comment]
mhh whats the type of the tx? just from the error message it looks like it might be expecting a uint8array and was given something else?

**Comment by shahidzebpay** [comment]
Ya i guess that is the solution. I am just not able to convert to that format. Tx is string passed via an API. for test like this 213331dasdad122as or anything as transaction id.
